### PR TITLE
see FPs where last_len = len

### PR DESCRIPTION
**Pull request by theflakes**
Added check for this so the script will exit if this is indeed the case.  Let me know if my reasoning is off.

### CODE REVIEW

**Comment by theflakes** [comment]
We are only watching port 80 and so far all have been Fps.  I was concerned about the case where the shooter matches the servers reply size but thought these were probably not the norm and/or harder to mimic consistently.

**Comment by yunzheng** [comment]
Ah ok, thanks for your feedback. I wonder if you get the same false positives using the rexmit_inconsistency patches.

Maybe you could also check if the packet contains any HTTP headers, else it's most likely a false positive.

**Comment by theflakes** [comment]
I would like to use the Bro patched version, but we are running
SecurityOnion and I don't have the time to install an out of band version
of Bro across all my sensors unfortunately.  But, thanks for working with
the Bro team on that patch, very much appreciated.

From my initial analysis the source of both packets for each alert were the
same source IP.  They ended up being TCP re-transmits.  More than likely
your QI script helped to indicate network issues we are having in this case.

I thought of adding both packet source IPs to the alert.  Would it be
beneficial to compare the source IPs to see if they are the same to try and
limit FPs? Or, have you seen instances in the wild where the shooter spoofs
the source IP on all of its packets?  Or, running a diff on the payload,
but that is potentially too operationally intensive.

Sorry, I try to get as as specific as I can with all my detection
mechanisms from the various tools I use.  Its always a trade off between
tolerable FPs, TPs, and the pesky indeterminable events.

**Comment by yunzheng** [comment]
I guess you could extend the policy to add some more tracking and only alert once per source IP to limit possible FP's.

The whole packet by the shooter is spoofed/crafted, as it needs to impersonate the server packet to the client. (so both source and dest ip + ports).
The payload is already being diffed/compared in the policy.

In the case of the FP's on your TCP retransmissions, how big are the packets? You could add a minimum length check and check if data contains 'HTTP/1.' to ensure it only matches on QI's on HTTP traffic.

**Comment by theflakes** [comment]
Thanks for clearing me up on the spoofed src, not sure why I was thinking
the src wouldn't be spoofed normally.

**Pull request closed without merging**
